version: "3.9"
services:
  #Postgres
  postgres:
    container_name: postgres
    #Build from /postgres file with Dockerfile
    build: ./postgres
    environment:
      #Using .env variables: ${.ENV VARIABLE TO BE USED}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_URL: ${POSTGRES_URL}

      # POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    #Default port for postgres is 5432
    ports:
      - "5432:5432"

  #Backend-API
  backend-api:
    container_name: backend-api
    build: ./
    volumes:
      - ./:/usr/src/app
    command: npm start
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
